title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: https://hayrikosem.github.io
color_scheme: dark
aux_links:
  Mikromax Mühendislik: https://www.mikromax.com.tr
